### ISSUE TITLE
Add any changes needed to data model for federated database

### ISSUE THREAD

**Issue by venitahagerty** [NOAA-GSL/VxData#8]
Currently, most documents in the model have a version. Does the data model need any changes for the federated database, particularly related to version? Will we have mixed versions in the same bucket? Will we require all federated users to upgrade their data and apps to stay in the federation? Can apps read multiple versions of documents? These questions need to be discussed and resolved sometime after the "steel thread" is completed.

**Comment by randytpierce** [comment]
It seems to be sufficient for the moment, we can close this and recreate an issue if there is a problem in the future.
